services:
 ocm_web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_PORT=${SERVICE_PORT}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: ocm_web
    expose:
      - "${SERVICE_PORT}"
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
